### ISSUE TITLE
Update from 1.33~ynh2 to 2.2.0~ynh1 failed

### ISSUE THREAD

**Issue by shakasan** [YunoHost-Apps/umami_ynh#11]
### Describe the bug

The update of umami from version 1.33~ynh2 to 2.2.0~ynh1 failed.

It seems related to the upstream project regarding the huge number of issues created recently.

### Context

- Hardware : OVH VPS, 4cores, 8Gb RAM, 80Gb HDD (usage <35%)
- YunoHost version : 11.1.18
- I have access to my server : through SSH, webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance? : no
- Using, or trying to install package version/branch : 2.2.0~ynh1
- If upgrading, current package version : 1.33~ynh2

### Steps to reproduce

Just click on the Update app button in webadmin

### Expected behavior

Successful update ;-)

### Logs

https://paste.yunohost.org/raw/ruquyolece

**Comment by ericgaspar** [comment]
https://github.com/YunoHost-Apps/umami_ynh/issues/7#issuecomment-1523183886

**Comment by shakasan** [comment]
Thanks for your answer.

Indeed, uninstall/re-install is fixing the issue.

Thanks a lot for your help.
