### ISSUE TITLE
Cannot install Umami due to errors with pgcrypto and other prisma-related packages

### ISSUE THREAD

**Issue by mdic** [YunoHost-Apps/umami_ynh#14]
### Describe the bug

App installation fails with errors that appear to be related to "permission denied to create extension "pgcrypto""

### Context

- Hardware: VPS bought online
- YunoHost version: 11.1.21.4
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 

### Steps to reproduce

- 
    ```sh
    sudo yunohost app umami
    ```
OR

- Install Umami from the webadmin

### Expected behavior

The app should install, however installation fails with exactly the same error on both CLI and webadmin installations. Also - I don't know if relevant - HD usage falls by ~5GB when trying to install.

### Logs
Erro log when trying to install from CLI: https://paste.yunohost.org/raw/binamafugi

Error log when trying to install from the webadmin: https://paste.yunohost.org/raw/misazixaga

**Comment by orhtej2** [comment]
Can you please test again with current `master`, `v2.6.2~ynh4`?

**Comment by mdic** [comment]
Problem solved with `v2.6.2~ynh4`, see also #29
