### ISSUE TITLE
Installation of 2.6.2 fails

### ISSUE THREAD

**Issue by mdic** [YunoHost-Apps/umami_ynh#29]
### Describe the bug

App installation fails with errors that appear to be related to "permission denied to create extension "pgcrypto""

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.4
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch:  

### Steps to reproduce

- Install Umami from the webadmin

### Expected behavior

The app should install, however installation fails with exactly the same error on both CLI and webadmin installations. Also - I don't know if relevant - HD usage falls by ~5GB when trying to install.

### Logs

https://paste.yunohost.org/raw/vagihevoko

**Comment by orhtej2** [comment]
Interesting, [`pgcrypto`](https://www.postgresql.org/docs/13/pgcrypto.html) should be provisionable by non-super users

**Comment by orhtej2** [comment]
Can you please test again with current `master`, `v2.6.2~ynh4`?

**Comment by orhtej2** [comment]
Also duplicate of your own #14

**Comment by mdic** [comment]
Hi @orhtej2 and thanks for the reply, with current master `v2.6.2~ynh4` the installation works like a charm.
